### ISSUE TITLE
[👉UNASSIGNED] Netlify Popup - Help not working

### ISSUE THREAD

**Issue by app-generator** [app-generator/free-site-builder#73]
> `STATUS`:  **ASSIGNED** to @umarali 
---

### Context

The Deployment popup should provide minimal help to the user.

> NOTE: This is a regression caused by the migration of the tool to NPM/CDN support 

@umarali please take a look.

TY!

![image](https://github.com/app-generator/free-site-builder/assets/51070104/74ded85a-d834-49b9-8d5c-75d405b31f0a)

**Comment by umarali** [comment]
Noted!

**Comment by umarali** [comment]
@app-generator the DNDBuilder error occurs before the popover toggle method is called, hence causing the popover to not toggle.

<img width="1438" alt="Screen Shot 2023-07-29 at 7 43 46 PM" src="https://github.com/app-generator/free-site-builder/assets/1346425/f0e12c48-3fc4-4fbc-9fc2-28fb140727e7">

**Comment by app-generator** [comment]
Yep, the type is not defined in that scope. 
Moreover, we have this Constructor in the `index.ts`:

```javascript
new DNDBuilder(
  {
    dropContainer: "dropzone",
    dropIndicator: "drop-here-indicator",
  },
  {
    actionPreview: "#action_preview",
    actionDownload: "#action_download",
    actionDeploy: "#action_deploy",
    closeModal: "#closeModal",
    fullScreenOption: "#fullScreenOption",
    tabletOption: "#tabletOption",
    mobileOption: "#mobileOption",
    deployForm: "#deployForm",
  }
);
```

In fact, the C-tor should be exposed by the library and called in the PAGE (script tag).

**Comment by app-generator** [comment]
@yurec133 The current implementation might require some fixes.
Please take a look.

**Comment by yurec133** [comment]
var builder = new DNDBuilder({
        dropContainer: 'dropzone',
        dropIndicator: 'drop-here-indicator'
    });  do not need to be used in index.html 
   new DNDBuilder  remove it from index.html 
   
   new DNDBuilder should be used only when using npm package

**Comment by umarali** [comment]
@yurec133 please take a look at the updated implementation and share your feedback. Thanks!
Closing this one.
