### ISSUE TITLE
VOLT Branch Issues

### ISSUE THREAD

**Issue by app-generator** [app-generator/free-site-builder#97]
Hello @ravirasadiya please pull the latest version of `kit-volt` branch and take a look at the following issues:

- modal not working on click 
- if possible, adjust the sidebar high to be the same as the main builder DropZone 
  - when empty, need to be at a minimum of 500px. 
-  profile -> card.html 
  - needs to have centered content  

In the rest, all is good.

TY!

**Comment by ravirasadiya** [comment]
okay

**Comment by app-generator** [comment]
- The `Clear` confirmation popup, display button with different sizes:

![image](https://github.com/app-generator/free-site-builder/assets/51070104/00d15a77-596b-44d8-87ad-86d6b104b6b2)

**Comment by ravirasadiya** [comment]
okay, let me check.

**Comment by ravirasadiya** [comment]
Done and pushed

**Comment by app-generator** [comment]
Validated. Closing.
TY @ravirasadiya
